typst-jp/docs

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
close #13
上記のIssueに関連して、Issueテンプレートを翻訳プロジェクトに特化したものに変更しました。この変更を叩き台としてさまざまな意見を頂ければと思います。
> chore: Issueテンプレートを独自のものに変更

- .github/workflows/deploy.yml
Cargo のバージョンが 1.80 ではCIがコケていましたので、暫定的にバージョン 1.77 に固定しました。
根本的な解決としては [Cargo.toml](https://github.com/typst-jp/typst-jp.github.io/blob/719ab4b9a62360afb453cc3f5127ebfc511102a9/Cargo.toml) を整備して Cargo.lock を更新する必要がありそうです。
> ci: pin cargo version to 1.77

- README.md
翻訳進捗を手動で追加しています。理想は自動化ですが、どうやらIssue APIにはIssueのタスク完成度データが含まれないっぽい（ほんまか？）から、手動でパースする必要がありそうです。
> docs: Add manual progress indicator

- docs/src/html.rs
Fixes #46 
日本語の文字など英数字（ASCII）が含まれているMarkdown見出しに対し、`heck`パッケージの変換を通した`id`ではなく（通してしまうと英字以外が消されてしまうため）、そのまま`title`を使うようにしました。
`title`以外のものを目次にする場合は不便でしょうが、今のところ見出しをそのまま右に使っても構わないと判断したため、そのまま使うようにしました。また、`title`が長いことが多いので、Reactの日本語ドキュメントのように文字サイズを小さくするほうが将来的に良さそうかもしれません。
> chore: Use title as `name` for non-ascii titles

- docs/src/lib.rs
- #62 のときに、気づけなくてすみません。
- glossaryのページが消えていたことに気づいたので修正しました。
v0.12.0のマージ前のコミットを見ると以下の通りで、
https://github.com/typst-jp/typst-jp.github.io/blob/4463badc4222b4e4fc4ff709168686a16e6d1774/docs/src/lib.rs#L88-L103
97行目の
```
packages_page(resolver), 
```
までは現在と同じで、
98行目の
```
md_page(resolver, base, load!("changelog.md")), 
```
は
```
changelog_pages(resolver),
```
に変更されています。
99, 100行目は https://github.com/typst-jp/typst-jp.github.io/pull/62#issue-2600243619 にありますように、削除されていて正常だと思います。
> upstreamの[v0.12.0](https://github.com/typst/typst/tree/v0.12.0)をマージした
RoadmapとCommunityのページは https://github.com/typst/typst/commit/cd02ae709f66742b6f50d6b84315feb8a7156d77#diff-6a17656d764b8e1930354f341cf7f47960b63845c3046edcd8bbf282aaa2f464 で削除された
以上の理解で、
```
md_page(resolver, base, load!("glossary.md")), 
``` …
> Restore glossary page

- docs/tutorial/1-writing.md
- docs/tutorial/2-formatting.md
- docs/tutorial/3-advanced.md
- docs/tutorial/4-template.md
- #63 の対応を行いました。
- tutorialの各マークダウンファイルの2行目をwelcome.mdと同一の`description: Typst チュートリアル`に統一しました。
https://github.com/typst-jp/typst-jp.github.io/blob/69f9d4179b947891bcd2a7490d7677f91543c5c6/docs/tutorial/welcome.md?plain=1#L1-L5
> Translate tutorial 3 advanced

- static/scripts/docs.js
close #48
- sidebarの開閉処理のコメントアウトを外した
- SPサイズの環境でsidebarの開閉ができる
- PCでは[DevTools](https://developer.chrome.com/docs/devtools)でSPサイズでの挙動を確認できます
> fix: sidebarの開閉処理を有効化

- .devcontainer/Dockerfile
DevContainer内でもgitやGitHubを使いたい場面が多かったため追加してみました。
VS CodeではDevContainer内でのcommitなどの操作に対してはローカルの設定を使ってくれるため、コンテナ内でのgitの設定は不要でした。
pullやpushなどをするときにはssh接続しますので、そのクライアントが必要なようでした。
以上により、gitとopenssh-clientをapt-get installに加えました。
参考
https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials
> Add git and openssh in devcontainer

- static/styles/docs.css
PCサイズの画面幅の環境において、ページの右上に位置している×ボタンは黄色のアラートを閉じるためのボタンのように見えますが、実際にはマークアップ上ではsidebarを閉じるためのボタンであり、#73 でsidebarの開閉のイベントを有効にしたことで、PCサイズの環境で意図しない挙動になってしまっていたため、画面の横幅が`600px`以上のときに×ボタンの要素を非表示にする対応を行いました。
- SPサイズの環境でsidebarを開閉できる
- 画面の横幅が`600px`以上のときに×ボタンが表示されない
> fix: 画面の横幅が`600px`以上のときにsidebarを閉じるボタンを非表示にするスタイルを追加

- docs/japanese.md
cf. #9
- 本文が「WIP」のまま放置を続けるのは問題なので、日本語ユーザーガイドの叩き台を作成した
- 叩き台の文章として適切である
- 将来的には、現在のTypstでのCJK組版の課題や、よくある質問集などを追加しようと考えています
> docs: 日本語ユーザーガイドの叩き台を作成

- .gitignore
- #71 で環境構築すると.venvディレクトリが生成され、それがgit管理に入ってしまうので.gitignoreファイルに追記しました。
- `# mise`とコメントアウトをふりましたが、`# Python`や`# uv`の方がよいですかね？
> Update `.gitignore` to include `.venv` directory

- crates/typst/src/visualize/image/mod.rs
- crates/typst/src/visualize/image/raster.rs
- docs/reference/syntax.md
- 翻訳対象：https://typst.app/docs/reference/visualize/image/
- お手元の環境では http://localhost:8000/docs/reference/visualize/image/ でご確認ください。
> Translation: visualize image

- crates/typst/src/model/figure.rs
- 翻訳対象：https://typst.app/docs/reference/model/figure/
- お手元の環境では http://localhost:8000/docs/reference/model/figure/ でご確認ください。
- #81 を参考に翻訳しました。
- `figure`は「図表」と訳しました。[用語集](https://typst-jp.github.io/docs/glossary/)に従っております。
個人的に悩んだところ
> Translation: model figure

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/tasks.json
- #69 でDevcontainer上でも開発が行えるようになりましたが、Devcontainer上でビルドしてしまうと生成物がroot権限で作られます。
- Devcontainer外で、例えば`mise run generate`などをするとファイルが上書きできずにエラーとなってしまいます。
- そのため https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user を参考に、rootでない一般ユーザーである`typst-jp`ユーザーを作成しました。
- `mise run preview`に合わせてWebサーバーのコマンドを`python3 -m http.server -d dist`に変更しました。それに伴いNode.jsのインストールは削除しました。 #83 が終わったら後追いでまた導入するかもしれませんが。
- `npx serve -n ./dist`ではポート番号が3000番でしたが、`python3 -m http.server -d dist`では8000番に変更されています。問題ないでしょうか？
- Ubuntu 22.04 ネイティブでテストした際に https://gist.github.com/Seasawher/18f5781e372e4fbe691ee8942828bd8e と同じ問題が発生したため、`"postCreateCommand": "git config --global --add safe.directory ${containerWorkspaceFolder}",`を追加しました。
> Fix devcontainer to non root user

- templates/group_template.html.j2
- [reference/math/variants/](https://typst-jp.github.io/docs/reference/math/variants/)などの`docs/reference/groups.yml`で管理されているページの見出しが本家と異なっていたため、テンプレートの見出しを修正した
> fix: groupのテンプレートの見出しの不要な文字を削除

- crates/typst/src/model/bibliography.rs
- #87 の一部です。
- `.textlintignore`の`dist/docs/reference/model/bibliography/index.html`をコメントアウトして`bun run textlint-html`を実施して https://github.com/typst-jp/typst-jp.github.io/pull/83#pullrequestreview-2490598082 以外のエラーが出ないようにしています。
- 他のファイルのlintエラーは #89 で対応します。
> model-bibliographyの翻訳

- docs/japanese/articles.md
- docs/japanese/packages.md
- docs/japanese/templates.md
- docs/japanese/welcome.md
- docs/src/lib.rs
- docs/src/link.rs
- 親ページのタイトルを翻訳した
- 翻訳に伴い、日本語ユーザーガイドのタイトルを変更した
> feat: 親ページのタイトルを翻訳

- gen.py
- templates/func_template.html.j2
- templates/group_template.html.j2
- templates/macros.html.j2
- templates/type_template.html.j2
- 型情報のリンクが古いままになっており、リンク切れを起こしていたため、正しいページに遷移できるように修正した
> fix: 型情報へのリンクを修正

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .vscode/tasks.json
- Devcontainer内でも #83 で追加したtextlintを使用できるようにしました。
- `.vscode/tasks`からも実行できるようにしています。
- `.devcontainer/README.md`の内容が実行できるかご確認いただけますと幸いです。
> chore: add textlint to devcontainer

- crates/typst/src/model/reference.rs
[reference/model/ref/](https://typst.app/docs/reference/model/ref/)の翻訳です。
> `docs/reference/model/ref/`の翻訳

- .vscode/tasks.json
VS Codeでgenerate-docsするタスクをデフォルトのビルドとして設定することで、ショートカットキー`Ctrl+Shift+B`で実行できるようしました。
参考：https://code.visualstudio.com/docs/editor/tasks#_typescript-hello-world
> chore: add build group property to generate-docs task

- crates/typst/src/model/cite.rs
- close #87 
ご確認お願いいたします。
textlintは`.textlintignore`で無視されているため、手元の環境では以下をコメントアウトをして確認しました。
https://github.com/typst-jp/typst-jp.github.io/blob/b1e2eeba232bbf9b3247dca6c6f41541ef0ee07a/.textlintignore#L3
> translate model-cite

- crates/typst-library/src/model/bibliography.rs
close #124 
以下の部分の空白（スペース）を詰めています。こちらの対応でよろしいでしょうか？
```
Hayagriva `.yml`やBibLaTeX` .bib`
```
ではなく
```
Hayagriva`.yml`やBibLaTeX`.bib`
```
としています。
> bibliography sourcesの翻訳

- crates/typst-library/src/layout/place.rs
- crates/typst-library/src/model/figure.rs
> Figureの追加翻訳

- website/src/components/ui/common/Header.tsx
現在のドキュメントのバージョンを明示することは以前から要請されており、バージョン表記がページ内に存在しないのは実用上でも不便なので、バージョン表記をヘッダーに追加して常にバージョン情報を閲覧できるようにしました。
> feat: Webサイトのヘッダーにバージョン表記を追加

- .mise.toml
以前他のissueかpull requestでもお聞きしましたが、miseにRustのバージョン管理も含めてもよいか再度ご検討いただけますでしょうか？
experimentalではありますが、Docker上で動作を確認できました。
https://mise.jdx.dev/lang/rust.html
もし他に悪影響を与えていなければ入れていただけますと幸いです。
- #138 の対応がやりやすくなります。
https://mise.jdx.dev/mise-cookbook/docker.html を参考にDockerでmiseのコンテナーを作成
```
docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest
```
docker内で以下のコマンドで環境構築
```
git clone -b feature/add-rust-in-mise https://github.com/typst-jp/typst-jp.github.io.git
cd typst-jp.github.io
mise trust
mise install
```
ビルドの確認
```
mise run generate
```
`mise run preview`を試すためには`docker run`にポート設定が必要になるかと思いますが、Rustに無関係かと思い試していません。
[tools]に関して、推奨の記述順序あればご指示ください。
> chore: Rustのバージョンを.mise.tomlに記載

- .github/workflows/deploy.yml
cf. https://github.com/typst-jp/typst-jp.github.io/pull/147
> ci: Rustツールチェーンのセットアップを削除

- website/src/globals.css
close https://github.com/typst-jp/typst-jp.github.io/issues/143
- インラインのcode要素のスタイルをGitHub風に変更した
> feat: インラインコードのスタイルをGitHub風に変更

- crates/typst-library/src/math/accent.rs
[reference/math/accent](https://typst.app/docs/reference/math/accent/)の翻訳です。
> `docs/reference/math/accent/`の翻訳

- docs/reference/language/scripting.md
[scripting](https://typst-jp.github.io/docs/reference/scripting/)のページに未翻訳の英文が残っていたため追加翻訳を行いました。ただ、翻訳した箇所の「剰余」および「calc」の部分のリンクが正しく機能しておらず、プレビューを行った際にはトップページに飛ばされてしまったため修正案を教えていただけるとありがたいです。(翻訳前の時点でもクリックすると404が表示されていましたが...)
> scripting(スクリプト記述)の追加翻訳

- crates/typst-library/src/math/root.rs
- docs/reference/groups.yml
- website/translation-status.json
[/math/roots](https://typst.app/docs/reference/math/roots)の翻訳です。
> `/docs/reference/math/roots`の翻訳

- crates/typst-library/src/layout/dir.rs
- website/translation-status.json
[`layout/direction`](https://typst.app/docs/reference/layout/direction/)の翻訳です
> `/docs/reference/layout/direction`の翻訳

- .github/workflows/website.yml
WebサイトのCIでのCargoの依存関係の解決を高速化するために、[Swatinem/rust-cache](https://github.com/Swatinem/rust-cache)を導入しました。
> ci: WebサイトのCIにrust-cacheを追加

- README.md
- website/src/components/ui/common/Header.tsx
close #24
close #170
- Webサイトのヘッダーに翻訳率の表示を追加
- READMEのバッジを削除
> feat: Webサイトに翻訳率を表示するバッジを追加

- website/src/components/templates/BaseTemplate.tsx
目次のリンクから見出しへ移動する際に、ヘッダーに被らない適切な位置にスクロールするよう修正しました。
> fix: 目次のリンクのスクロール位置を調整

- website/src/components/ui/common/SideNavigation.tsx
- website/src/components/ui/common/TableOfContents.tsx
cf. #192 
ヘッダーの縦幅に合わせてサイドナビゲーションの位置を調整しました。
> fix: サイドナビゲーションの位置を調整

- website/src/globals.css
close #145 
- コードブロックのスタイルをMonokai風に変更
- cf. https://textmate-grammars-themes.netlify.app/?theme=monokai&grammar=typst
> feat: WebサイトのコードブロックのスタイルをMonokai風に変更

- crates/typst-library/src/layout/stack.rs
- website/translation-status.json
[layout/stack](https://typst.app/docs/reference/layout/stack/)の翻訳です
> `/docs/reference/layout/stack`の翻訳

- website/src/components/icons/WorldIcon.tsx
- website/src/components/icons/index.ts
- website/src/components/templates/BaseTemplate.tsx
- website/src/components/ui/common/TranslationStatusAlert.tsx
close #158
- ページの上部と下部に原文へのリンクを追加した
> feat: Webサイトのページに原文へのリンクを追加

- website/src/components/templates/FuncTemplate.tsx
This PR will uncover _doubly_ nested definitions, which were previously hidden.
Resolves #234
1. `outline` is a function.
2. `outline.entry` is a function nested in `outline`
3. [`outline.entry.indented`](https://typst.app/docs/reference/model/outline/#definitions-entry-definitions-indented) is a function doubly nested in `outline`.
Currently, `indented`, `prefix`, and other definitions under `outline.entry` are missing in https://typst-jp.github.io/docs/reference/model/outline/. The last part on that page is `fill`, which is a parameter of `outline.entry`.
This PR will add those definitions.
- Official: https://typst.app/docs/reference/model/outline/
- Before: https://typst-jp.github.io/docs/reference/model/outline/
- After (preview with the upstream English dev docs): …
> fix: Show doubly nested definitions

- crates/typst-library/src/math/op.rs
- website/translation-status.json
[math/op](https://typst.app/docs/reference/math/op)の翻訳です。
> `/docs/reference/math/op`の翻訳

- crates/typst-library/src/math/attach.rs
- docs/reference/groups.yml
- website/translation-status.json
[math/attach](https://typst.app/docs/reference/math/attach)の翻訳です。
> `/docs/reference/math/attach`の翻訳

- crates/typst-library/src/math/matrix.rs
- website/translation-status.json
[math/vec](https://typst.app/docs/reference/math/vec)の翻訳です。
> `/docs/reference/math/vec`の翻訳

- crates/typst-library/src/model/list.rs
[model/list/](https://typst-jp.github.io/docs/reference/model/list/)において、#122 での訳でセクション名である"Exmple"が訳抜けしてしまっていたため、「例」と訳しました。
【修正前】
【修正後】
> `docs/reference/model/list/`の訳抜けの修正

- crates/typst-library/src/text/linebreak.rs
- website/translation-status.json
[text/linebreak](https://typst.app/docs/reference/text/linebreak)の翻訳です。
> `/docs/reference/text/linebreak`の翻訳

- crates/typst-library/src/model/outline.rs
- website/translation-status.json
- outline →訳出として「一覧」「概要」なども候補にありましたが、誤解が生じそうな場所もあったため、「アウトライン」に統一しました。
- inner contents →「内部コンテンツ」としました。コードの`inner`がそのまま置かれている場所と混ざってしまいましたが、初出で「内部（inner）コンテンツ」と表記することで対応しているつもりです。
- entry →「項目」としました。[footnoteのentry](https://typst-jp.github.io/docs/reference/model/footnote/#definitions-entry)と訳を揃えております。
> `/docs/reference/model/outline`の翻訳

- crates/typst-library/src/math/underover.rs
- docs/reference/groups.yml
- website/translation-status.json
[math/underover](https://typst.app/docs/reference/math/underover)の翻訳です。
> `/docs/reference/math/underover`の翻訳

- crates/typst-library/src/text/case.rs
- website/translation-status.json
[text/lower](https://typst.app/docs/reference/text/lower)および[text/upper](https://typst.app/docs/reference/text/upper)の翻訳です。
> `/docs/reference/text/lower`および`/docs/reference/text/upper`の翻訳

- docs/changelog/0.10.0.md
- docs/changelog/0.11.1.md
- docs/reference/language/syntax.md
Before:
- `$type/$function`
`reference/foundations/type/$function/`
After:
- `$function`
`reference/foundations/function/`
You can refer to the [official `syntax.md`](https://github.com/typst/typst/blob/c7938e93dcd63464912345c3d7363f5961c2f47d/docs/reference/language/syntax.md?plain=1#L116) for reference.
`typst-docs` did not panic, because it thought things after `/` are `#`-anchors. (The normal usage would be `$scripting/#loops`.)
The page `$pattern` does not exist anymore.
See also https://typst.app/docs/changelog/0.11.1/#export for reference.
> Fix broken links

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
- CONTRIBUTING.md
- README.en.md
- README.md
- website/src/metadata.ts
cf. https://github.com/typst-jp/docs/issues/233#issuecomment-3216418382
> docs: GitHubリポジトリのURLを移行先に置換

- crates/typst-library/src/text/shift.rs
- website/translation-status.json
[text/sub](https://typst.app/docs/reference/text/sub)および[text/super](https://typst.app/docs/reference/text/super)の翻訳です。
> `/docs/reference/text/sub`および`/docs/reference/text/super`の翻訳

- docs/reference/library/data-loading.md
- website/translation-status.json
[/data-loading](https://typst.app/docs/reference/data-loading/)の翻訳です。
プレビューでは定義セクションの一部が未訳になっていますが、他のPR(#280 ,#281 )がマージされたタイミングで和訳が反映されると思われます。
> `/docs/reference/data-loading/`の翻訳

- crates/typst-library/src/loading/yaml.rs
- website/translation-status.json
[/data-loading/yaml/](https://typst.app/docs/reference/data-loading/yaml/)の翻訳です。
> `/docs/reference/data-loading/yaml/`の翻訳

- website/src/components/templates/BaseTemplate.tsx
- website/src/components/ui/common/Header.tsx
- website/src/metadata.ts
cf. https://github.com/typst-jp/docs/issues/233#issuecomment-3247643784
> feat: add translation status display switcher

- docs/reference/language/syntax.md
> 上（下）付き添え字→上（下）付き文字に修正
